app/core/urls.py
from django.conf import settings
from django.urls import path, include
from app.core.views import supplier, company, brand, line, category, iva, product, product_price, product_price_detail, payment_method
from app.core.views.profile_view import ProfileView, UpdateProfileView
from app.core.views.generate_qr import QRCodeGeneratorView, GenerateLoginQRView, QRScannerView
from app.core.views.scaner_face import FacialRecognitionView
from app.core.views.recuperation_email import PasswordResetView

from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

app_name='core' # define un espacio de nombre para la aplicación
urlpatterns = [    
    # URLs de proveedores
    path('supplier_list/', supplier.SupplierListView.as_view() ,name='supplier_list'),
    path('supplier_create/', supplier.SupplierCreateView.as_view(),name='supplier_create'),
    path('supplier_update/<int:pk>/', supplier.SupplierUpdateView.as_view(),name='supplier_update'),
    path('supplier_delete/<int:pk>/', supplier.SupplierDeleteView.as_view(),name='supplier_delete'),
    # URLs de compañías
    path('company_list/', company.CompanyListView.as_view(),name='company_list'),
    path('company_create/', company.CompanyCreateView.as_view(),name='company_create'),
    path('company_update/<int:pk>/', company.CompanyUpdateView.as_view(),name='company_update'),
    path('company_delete/<int:pk>/', company.CompanyDeleteView.as_view(),name='company_delete'),
    # URLs de marcas
    path('brand_list/', brand.BrandListView.as_view(),name='brand_list'),
    path('brand_create/', brand.BrandCreateView.as_view(),name='brand_create'),
    path('brand_update/<int:pk>/', brand.BrandUpdateView.as_view(),name='brand_update'),
    path('brand_delete/<int:pk>/', brand.BrandDeleteView.as_view(),name='brand_delete'),
    # URLs de líneas
    path('line_list/', line.LineListView.as_view(),name='line_list'),
    path('line_create/', line.LineCreateView.as_view(),name='line_create'),
    path('line_update/<int:pk>/', line.LineUpdateView.as_view(),name='line_update'),
    path('line_delete/<int:pk>/', line.LineDeleteView.as_view(),name='line_delete'),
    # URLs de categorías
    path('category_list/', category.CategoryListView.as_view(),name='category_list'),
    path('category_create/', category.CategoryCreateView.as_view(),name='category_create'),
    path('category_update/<int:pk>/', category.CategoryUpdateView.as_view(),name='category_update'),
    path('category_delete/<int:pk>/', category.CategoryDeleteView.as_view(),name='category_delete'),
    # URLs de IVA
    path('iva_list/', iva.IvaListView.as_view(),name='iva_list'),
    path('iva_create/', iva.IvaCreateView.as_view(),name='iva_create'),
    path('iva_update/<int:pk>/', iva.IvaUpdateView.as_view(),name='iva_update'),
    path('iva_delete/<int:pk>/', iva.IvaDeleteView.as_view(),name='iva_delete'),
    # URLs de productos
    path('product_list/', product.ProductListView.as_view(),name='product_list'),
    path('product_create/', product.ProductCreateView.as_view(),name='product_create'),
    path('product_update/<int:pk>/', product.ProductUpdateView.as_view(),name='product_update'),
    path('product_delete/<int:pk>/', product.ProductDeleteView.as_view(),name='product_delete'),
    # URLs de precios de productos
    path('product_price_list/', product_price.ProductPriceListView.as_view(),name='product_price_list'),
    path('product_price_create/', product_price.ProductPriceCreateView.as_view(),name='product_price_create'),
    path('product_price_update/<int:pk>/', product_price.ProductPriceUpdateView.as_view(),name='product_price_update'),
    path('product_price_delete/<int:pk>/', product_price.ProductPriceDeleteView.as_view(),name='product_price_delete'),
    # URLs de detalles de precios de productos 
    path('product_price_detail_list/', product_price_detail.ProductPriceDetailListView.as_view(),name='product_price_detail_list'),
    path('product_price_detail_create/', product_price_detail.ProductPriceDetailCreateView.as_view(),name='product_price_detail_create'),
    path('product_price_detail_update/<int:pk>/', product_price_detail.ProductPriceDetailUpdateView.as_view(),name='product_price_detail_update'),
    path('product_price_detail_delete/<int:pk>/', product_price_detail.ProductPriceDetailDeleteView.as_view(),name='product_price_detail_delete'),
    # URLs de métodos de pago
    path('payment_method_list/', payment_method.PaymentMethodListView.as_view(),name='payment_method_list'),
    path('payment_method_create/', payment_method.PaymentMethodCreateView.as_view(),name='payment_method_create'),
    path('payment_method_update/<int:pk>/', payment_method.PaymentMethodUpdateView.as_view(),name='payment_method_update'),
    path('payment_method_delete/<int:pk>/', payment_method.PaymentMethodDeleteView.as_view(),name='payment_method_delete'),
    # URLs de Perfil
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    # URLs de QR
    path('generate-qr-page/<int:user_id>/', QRCodeGeneratorView.as_view(), name='generate_qr_page'),
    path('generate-qr/<int:user_id>/', GenerateLoginQRView.as_view(), name='generate_login_qr'),
    path('qr-scanner/', QRScannerView.as_view(), name='qr_scanner_view'),
    # URLs de Reconocimiento Facial
    path('facial-recognition/', FacialRecognitionView.as_view(), name='facial_recognition'),
    # URLs Recuperara Contraseña
    path('recover-password/', PasswordResetView.as_view(), name='password_reset'),
    # URLs Traduccion
    path('i18n/', include('django.conf.urls.i18n')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proy_sales/urls.py
from django.conf import settings
from django.conf.urls.static import static
from app.core import views as core
from django.contrib import admin
from django.urls import path, include
from app.core.views.home import HomeTemplateView
from app.core.views.modulos import ModuloTemplateView
urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('',HomeTemplateView.as_view(), name='home'),
    path('modulos/',ModuloTemplateView.as_view(), name='modulos'),
    path('security/', include('app.security.urls', namespace='security')),
    path('core/', include('app.core.urls', namespace='core')),
    path('sale/', include('app.sales.urls', namespace='sale')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/views.py
# from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
# from app.core.forms import ProductForm, BrandForm, SupplierForm, CategoryForm
# from app.core.models import Product, Brand, Supplier, Category
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from django .contrib.auth.models import User
# from django.contrib.auth import login, logout, authenticate
# from .forms import CustomUserCreationForm, CustomUserUpdateForm
# from django.contrib import messages
# from django.db.models import Q

# # PAGUINACION
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



# # ----------------- Perfil -----------------
# def profile(request):
#     data = {"title1": "IC - Perfil",
#             "title2": "Perfil de Usuario"}
#     return render(request, 'core/profile.html', data)

# #  Actualizar perfil 
# def update_profile(request):
#     data = {"title1": "IC - Actualizar Perfil",
#             "title2": "Actualizar Perfil"}
#     if request.method == 'POST':
#         form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)
#         if form.is_valid():
#             form.save()
#             messages.success(request, '¡Tu perfil ha sido actualizado exitosamente!')
#             return redirect('profile')
#     else:
#         form = CustomUserUpdateForm(instance=request.user)
    
#     return render(request, 'core/update_profile.html', {'form': form, **data})

# # ----------------- Registro -----------------
# def signup(request):
#     data = {"title1": "IC - Registro",
#             "title2": "Registro de Usuarios"}

#     if request.method == "GET":
#         form = CustomUserCreationForm()
#         return render(request, "registration/signup.html", {"form": form, **data})
#     elif request.method == "POST":
#         form = CustomUserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             # login(request, user)
#             messages.success(
#                 request, '¡Registro exitoso! Por favor, inicia sesión.')
#             return redirect("signin")
#         else:
#             # Manejo de errores específicos
#             if form.errors:
#                 error_messages = []
#                 for field in form:
#                     for error in field.errors:
#                         error_messages.append(f"{field.label}: {error}")
#                 for error in form.non_field_errors():
#                     error_messages.append(error)
#                 data["errors"] = error_messages

#             return render(request, "registration/signup.html", {"form": form, **data})

# # ----------------- Cerrar Sesion -----------------
# def signout(request):
#     logout(request)
#     return redirect("core:home")

# # ----------------- Iniciar Sesion -----------------
# def signin(request):
#     data = {"title1": "IC - Inicio de Sesión",
#             "title2": "Inicio de Sesión"}

#     if request.method == "GET":
#         # Obtener mensajes de éxito de la cola de mensajes
#         success_messages = messages.get_messages(request)
#         return render(request, "registration/signin.html", {
#             "form": AuthenticationForm(),
#             "success_messages": success_messages,  # Pasar mensajes de éxito a la plantilla
#             **data
#         })
#     else:
#         form = AuthenticationForm(data=request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect("core:home")
#             else:
#                 return render(request, "registration/signin.html", {
#                     "form": form,
#                     "error": "El usuario o la contraseña son incorrectos",
#                     **data
#                 })
#         else:
#             return render(request, "registration/signin.html", {
#                 "form": form,
#                 **data
#             })

# # ----------------- Vistas de Home -----------------
# def home(request):
#     data = {"title1": "IC - Inicio",
#             "title2": "Iguanas Corporation"}
#     # Obtener el estado de autenticación del usuario
#     is_authenticated = request.user.is_authenticated
#     # Agregar el estado de autenticación al contexto
#     data["is_authenticated"] = is_authenticated
#     return render(request, 'core/home.html', data)

# # ----------------- Vistas de Productos -----------------
# def product_List(request):
#     data = {"title1": "IC - Productos", "title2": "Consulta de Productos"}
    
#     query = request.GET.get('q')
#     if query:
#         products_list = Product.objects.filter(Q(description__icontains=query) | Q(id__icontains=query))
#     else:
#         products_list = Product.objects.all()

#     paginator = Paginator(products_list, 5)  # Muestra 10 productos por página
#     page = request.GET.get('page')
#     try:
#         products = paginator.page(page)
#     except PageNotAnInteger:
#         products = paginator.page(1)
#     except EmptyPage:
#         products = paginator.page(paginator.num_pages)

#     data["products"] = products
#     return render(request, "core/products/list.html", data)

# def product_create(request):
#     data = {"title1": "IC - Crear Productos", "title2": "Ingreso De Productos"}

#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             product = form.save(commit=False)
#             product.user = request.user  # Asignar el usuario actual
#             product.save()  # Guardar el producto principal

#             # Guardar las relaciones ManyToMany (categorías)
#             form.save_m2m()

#             messages.success(request, f"Éxito al crear el producto {product.description}.")
#             return redirect("core:product_list")
#     else:
#         form = ProductForm()

#     # Si el formulario no es válido o es una solicitud GET, mostrar el formulario con los datos actuales
#     data["form"] = form
#     return render(request, "core/products/form.html", data)


# # Editar un producto
# def product_update(request, id):
#     data = {"title1": "IC - Actualizar Productos", "title2": "Edicion De Productos"}
#     product = Product.objects.get(pk=id)
#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             messages.success(request, f"Éxito al actualizar el producto {product.description}.")
#             return redirect("core:product_list")
#     else:
#         form = ProductForm(instance=product)
#     data["form"] = form
#     return render(request, "core/products/form.html", data)

# # Eliminar un producto
# def product_delete(request, id):
#     product = Product.objects.get(pk=id)
#     data = {"title1": "IC - Eliminar Productos",
#             "title2": "Eliminar Un Producto", "product": product}
#     if request.method == "POST":
#         product.delete()
#         messages.success(request, f"Éxito al eliminar el producto.")
#         return redirect("core:product_list")
#     return render(request, "core/delete.html", data)

# # ----------------- Vistas de Marcas -----------------
# def brand_List(request):
#     data = {"title1": "IC - Marcas", "title2": "Consulta de Marcas"}
#     brands = Brand.objects.all()
#     data["brands"] = brands
#     # Pasar los mensajes al contexto de la plantilla
#     data["messages"] = messages.get_messages(request)
#     return render(request, "core/brands/list.html", data)

# # Crear una marca
# def brand_create(request):
#     data = {"title1": "IC - Crear Marcas", "title2": "Ingreso de Marca"}
#     if request.method == "POST":
#         form = BrandForm(request.POST)
#         if form.is_valid():
#             # Asignar el usuario actual al campo user de la marca
#             brand = form.save(commit=False)
#             brand.user = request.user
#             brand.save()
#             # Agregar mensaje de éxito
#             messages.success(request, f"Éxito al crear la marca {brand.description}.")
#             return redirect("core:brand_list")
#     else:
#         form = BrandForm()
#     data["form"] = form
#     return render(request, "core/brands/form.html", data)

# # Editar una marca
# def brand_update(request, id):
#     data = {"title1": "IC - Editar Marcas", "title2": "Edicion De Marcas"}
#     brand = Brand.objects.get(pk=id)
#     if request.method == "POST":
#         form = BrandForm(request.POST, request.FILES, instance=brand)
#         if form.is_valid():
#             form.save()
#             # Agregar mensaje de éxito
#             messages.success(request, f"Éxito al actualizar la marca {brand.description}.")
#             return redirect("core:brand_list")
#     else:
#         form = BrandForm(instance=brand)

#     data["form"] = form
#     return render(request, "core/brands/form.html", data)

# # Eliminar una marca
# def brand_delete(request, id):
#     brand = Brand.objects.get(pk=id)
#     data = {"title1": "IC - Eliminar Marcas", "title2": "Eliminar Una Marca", "brand": brand}
#     if request.method == "POST":
#         brand.delete()
#         messages.success(request, f"Éxito al eliminar la marca.")
#         return redirect("core:brand_list")
#     return render(request, "core/delete.html", data)

# # ----------------- Vistas de Proveedores -----------------
# def supplier_List(request):
#     data = {"title1": "IC - Proveedores", "title2": "Consulta de Proveedores"}

#     query = request.GET.get('q')
#     if query:
#         suppliers_list = Supplier.objects.filter(

app/core/views/home.py
from app.security.instance.menu_module import MenuModule
from app.security.mixins.mixins import PermissionMixin
from django.views.generic import TemplateView

class HomeTemplateView(TemplateView):
    
    
    template_name = 'components/home.html'
    
    def get_context_data(self, **kwargs):
        # context = super().get_context_data(**kwargs)
        context = {"title1": "IC - Inicio",
            "title2": "Corporacion el Rosado"}
        
        return context

templates/core/ivas/form.html
{% extends 'components/base.html' %}
{% block content %}
  {% load static %}
  <title>
    {% block title %}
      {{ title }}
    {% endblock %}
  </title>
  <section class="dark:bg-principal mt-20">
    <div class="text-center" data-aos="fade" data-aos-delay="200">
      <div class="sm:pt-28 lg:pt-4">
        <h1 class="dark:text-white text-4xl text-center mt-6 font-Pacifico">{{ title }}</h1>
      </div>
      <form method="post" enctype="multipart/form-data" class="space-y-6 py-4">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mx-4 lg:mx-20" data-aos="fade">
          <!-- Columna de la izquierda -->
          <div class="bg-white dark:bg-secundario rounded-3xl flex flex-col justify-center items-center p-8" data-aos="fade-right" data-aos-delay="200">
            <div class="w-[60%] text-center">
              <h2 class="dark:text-blue-300 text-2xl text-center mt-6 font-Pacifico">Imagen de IVA</h2><br />
              <div id="imagenPreview">
                {% if form.image.value %}
                  <img id="imagenSeleccionada" src="{{ form.image.value.url }}" class="mx-auto d-block rounded-lg" alt="Imagen de IVA" />
                {% else %}
                  <img id="imagenSeleccionada" src="{% static 'img/models/default_iva.jpg' %}" class="mx-auto d-block rounded-lg" alt="Imagen de IVA por defecto" />
                {% endif %}
              </div>
            </div>
            <div class="text-center w-auto m-4">
              <label for="{{ form.image.id_for_label }}" class="dark:text-blue-300 font-black uppercase text-lg">{{ form.image.label }}</label>
              {{ form.image }}
            </div>
          </div>
          <!-- Columna de la derecha -->
          <div class="p-4 rounded-3xl dark:bg-secundario bg-white flex flex-col justify-center items-center" data-aos="fade-right" data-aos-delay="200">
            {% csrf_token %}
            <div class="mb-8">
              <label for="{{ form.description.id_for_label }}" class="dark:text-blue-300 font-black uppercase text-lg">{{ form.description.label }}</label>
              {{ form.description }}
            </div>
            <div class="mb-8">
              <label for="{{ form.value.id_for_label }}" class="dark:text-blue-300 font-black uppercase text-lg">{{ form.value.label }}</label>
              {{ form.value }}
            </div>
            <div class="mb-8 flex flex-col justify-center items-center">
              <label for="{{ form.active.id_for_label }}" class="dark:text-blue-300 font-black uppercase text-lg">{{ form.active.label }}</label>
              {{ form.active }}
            </div>
            <div class="flex flex-col md:flex-row justify-center">
              <button type="submit" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center"><i class="fa-solid fa-save mr-2"></i>Guardar</button>
              <a class="bg-red-700 hover:bg-red-800 text-white py-2 px-4 rounded-full flex items-center" href="{% url 'core:iva_list' %}"><i class="fa-solid fa-xmark mr-2"></i>Cancelar</a>
            </div>
          </div>
        </div>
      </form>
    </div>
  </section>

  <script>
    const imagenInput = document.getElementById('{{ form.image.id_for_label }}')
    const imagenSeleccionada = document.getElementById('imagenSeleccionada')
    
    imagenInput.addEventListener('change', function () {
      const file = imagenInput.files[0]
      if (file) {
        const reader = new FileReader()
        reader.onload = function (e) {
          imagenSeleccionada.src = e.target.result
        }
        reader.readAsDataURL(file)
      } else {
        ;('{% if form.image.value %}')
        imagenSeleccionada.src = '{{ form.image.value.url }}'
        ;('{% else %}')
        imagenSeleccionada.src = "{% static 'img/models/default_iva.jpg' %}"
        ;('{% endif %}')
      }
    })
  </script>
{% endblock %}

templates/core/ivas/list.html
{% extends 'components/base.html' %}
{% block content %}
  {% load static %}
  <title>
    {% block title %}
      {{ title1 }}
    {% endblock %}
  </title>
  <section class="dark:bg-principal mt-20">
    <div class="text-center" data-aos="fade-up" data-aos-delay="200">
      <div class="sm:pt-28 lg:pt-24">
        <div class="flex flex-col items-center justify-center">
          <span class="rounded-full bg-indigo-500 px-2 py-1 text-white uppercase text-sm">{{ title1 }}</span>
        </div>
        <h1 class="dark:text-white text-4xl text-center mt-6 font-Pacifico">{{ title2 }}</h1>
      </div>
      <!-- Barra de búsqueda -->
      <div class="p-4 flex justify-center">
        <label for="table-search" class="sr-only">Search</label>
        <div class="relative mt-1">
          <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
            </svg>
          </div>
          <form method="GET" action="{% url 'core:iva_list' %}">
            <input type="text" name="q" id="table-search" class="text-center pl-10 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 pr-12 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" placeholder="Búsqueda" value="{{ request.GET.q }}" />
          </form>
        </div>
      </div>
      <div class="m-4 lg:m-8 sm:mx-40 sm:my-2 lg:grid lg:grid-cols-4 gap-8 lg:mx-20 lg:p-4 rounded-3xl" data-aos="fade-up" data-aos-delay="200">
        {% for item in ivas %}
          <div class="mb-4 flex justify-center custom-transform">
            <div class="dark:bg-secundario relative w-full overflow-hidden rounded-lg border border-gray-100 bg-white shadow-md dark:border-none">
              <div class="dark:bg-secundario text-center card card-custom">
                <h2 class="dark:text-blue-400 text-2xl text-center mt-6 font-black uppercase font-Tiny5">{{ item.description }}</h2>
                <div class="dark:bg-contenedores p-4 card-body flex flex-col justify-center items-center">
                  <img src="{% if item.image %}
                      {{ item.image.url }}
                    {% else %}
                      {% static 'img/models/default_iva.jpg' %}
                    {% endif %}"
                    class="w-32 h-32 rounded-2xl p-2"
                    alt="{{ item.name }}" />
                  <p class="dark:text-blue-300 font-Pacifico">
                    Valor: <span class="font-light font-Quicksand dark:text-gray-400">{{ item.value }}</span>
                  </p>

                  <p class="dark:text-blue-300 font-Pacifico">
                    Estado: <span class="font-light font-Quicksand dark:text-gray-400">
                      {% if item.active %}
                        <i class="fa-solid fa-check text-green-500"></i>
                      {% else %}
                        <i class="fa-solid fas fa-eye-slash text-red-500"></i>
                      {% endif %}
                    </span>
                  </p>
                </div>
                <div class="dark:bg-contenedores card-footer flex flex-col md:flex-row justify-center items-center">
                  {% if permissions.change_iva %}
                    <a href="{% url 'core:iva_update' item.id %}" class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center"><i class="fa-solid fa-gear mr-2"></i> Editar</a>
                  {% endif %}
                  {% if permissions.delete_iva %}
                    <button class="bg-red-700 hover:bg-red-800 text-white py-2 px-4 rounded-full flex items-center" onclick="openDeleteModal('{{ item.id }}', '{{ item.description }}')"><i class="fa-solid fa-trash mr-2"></i> Eliminar</button>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- Paginación -->
      <div class="flex justify-center mt-4">
        <nav aria-label="Page navigation example">
          <ul class="inline-flex -space-x-px">
            {% if page_obj.has_previous %}
              <li>
                <a href="?page=1" class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Anterior</a>
              </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
              <li>
                <a href="?page={{ num }}"
                  class="flex items-center justify-center px-3 h-8 leading-tight {% if num == page_obj.number %}
                    text-blue-600 bg-blue-50 border border-gray-300 hover:bg-blue-100 hover:text-blue-700 dark:bg-secundario dark:border-principal dark:text-blue-300
                  {% else %}
                    text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white
                  {% endif %}">
                  {{ num }}
                </a>
              </li>
            {% endfor %}
            {% if page_obj.has_next %}
              <li>
                <a href="?page={{ page_obj.next_page_number }}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Siguiente</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>

      <!-- Enlaces adicionales -->
      <div class="flex flex-col md:flex-row justify-center form-group text-center p-4">
        {% if permissions.add_iva %}
          <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center justify-center" href="{% url 'core:iva_create' %}"><i class="fa-solid fa-plus mr-2"></i> Nuevo IVA</a>
        {% endif %}
        <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center" href="{% url 'home' %}"><i class="fa-solid fa-house"></i></a>
      </div>
    </div>
  </section>

  {% include 'core/delete.html' %}
  <script>
    function openDeleteModal(id, name) {
      const deleteForm = document.getElementById('deleteForm')
      deleteForm.action = `{% url 'core:iva_delete' 0 %}`.replace('0', id)
      document.getElementById('Description').textContent = `ID: ${id} - ${name}`
      document.getElementById('deleteModal').classList.remove('hidden')
    }
    function closeModal() {
      document.getElementById('deleteModal').classList.add('hidden')
    }
  </script>
{% endblock %}